USE [mumdab]
GO
INSERT INTO [employee].[empinfr]([EMP_ID],[INF_DATE],[INF_REASON])VALUES('105','2005-05-31','Leave taken without prior notice')
INSERT INTO [employee].[empinfr]([EMP_ID],[INF_DATE],[INF_REASON])VALUES('162','2008-01-21','Negative feedback from the customer')
INSERT INTO [employee].[empinfr]([EMP_ID],[INF_DATE],[INF_REASON])VALUES('105','2009-05-14','Negative feedback from the customer')
INSERT INTO [employee].[empinfr]([EMP_ID],[INF_DATE],[INF_REASON])VALUES('145','2010-09-17','Delay in Delivery')
INSERT INTO [employee].[empinfr]([EMP_ID],[INF_DATE],[INF_REASON])VALUES('162','2011-12-15','Leave taken without prior notice')
INSERT INTO [employee].[empinfr]([EMP_ID],[INF_DATE],[INF_REASON])VALUES('135','2012-03-04','Misdemeanor at work')
INSERT INTO [employee].[empinfr]([EMP_ID],[INF_DATE],[INF_REASON])VALUES('112','2013-04-25','Leave taken without prior notice')
INSERT INTO [employee].[empinfr]([EMP_ID],[INF_DATE],[INF_REASON])VALUES('194','2014-03-26','Negative feedback from the customer')
INSERT INTO [employee].[empinfr]([EMP_ID],[INF_DATE],[INF_REASON])VALUES('129','2014-07-10','Leave taken without prior notice')
INSERT INTO [employee].[empinfr]([EMP_ID],[INF_DATE],[INF_REASON])VALUES('181','2015-02-27','Leave taken without prior notice')
INSERT INTO [employee].[empinfr]([EMP_ID],[INF_DATE],[INF_REASON])VALUES('120','2015-07-28','Misplaced the Dabba')
INSERT INTO [employee].[empinfr]([EMP_ID],[INF_DATE],[INF_REASON])VALUES('129','2015-09-05','Leave taken without prior notice')
INSERT INTO [employee].[empinfr]([EMP_ID],[INF_DATE],[INF_REASON])VALUES('148','2015-09-11','Leave taken without prior notice')
INSERT INTO [employee].[empinfr]([EMP_ID],[INF_DATE],[INF_REASON])VALUES('130','2015-12-23','Delay in Delivery')
INSERT INTO [employee].[empinfr]([EMP_ID],[INF_DATE],[INF_REASON])VALUES('194','2016-07-15','Misplaced the Dabba')
INSERT INTO [employee].[empinfr]([EMP_ID],[INF_DATE],[INF_REASON])VALUES('129','2016-11-18','Misplaced the Dabba')
INSERT INTO [employee].[empinfr]([EMP_ID],[INF_DATE],[INF_REASON])VALUES('148','2016-11-30','Negative feedback from the customer')
INSERT INTO [employee].[empinfr]([EMP_ID],[INF_DATE],[INF_REASON])VALUES('197','2017-02-18','Negative feedback from the customer')
INSERT INTO [employee].[empinfr]([EMP_ID],[INF_DATE],[INF_REASON])VALUES('148','2018-01-19','Leave taken without prior notice')
INSERT INTO [employee].[empinfr]([EMP_ID],[INF_DATE],[INF_REASON])VALUES('181','2018-08-22','Misplaced the Dabba')
INSERT INTO [employee].[empinfr]([EMP_ID],[INF_DATE],[INF_REASON])VALUES('151','2019-01-09','Leave taken without prior notice')
INSERT INTO [employee].[empinfr]([EMP_ID],[INF_DATE],[INF_REASON])VALUES('120','2019-02-01','Leave taken without prior notice')
INSERT INTO [employee].[empinfr]([EMP_ID],[INF_DATE],[INF_REASON])VALUES('194','2019-05-04','Misdemeanor at work')
