USE [mumdab]
GO
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2010-01-31', REASON = 'Service discontinuation' WHERE CUST_ID = '113'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2009-07-22', REASON = 'Service discontinuation' WHERE CUST_ID = '122'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2018-09-10', REASON = 'Relocation' WHERE CUST_ID = '140'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2000-10-16', REASON = 'Opted for other services' WHERE CUST_ID = '146'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '1999-01-17', REASON = 'Relocation' WHERE CUST_ID = '249'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2017-12-31', REASON = 'Opted for other services' WHERE CUST_ID = '253'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2017-01-03', REASON = 'Service discontinuation' WHERE CUST_ID = '285'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '1998-04-25', REASON = 'Service discontinuation' WHERE CUST_ID = '288'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2009-04-20', REASON = 'Opted for other services' WHERE CUST_ID = '297'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2009-08-31', REASON = 'Opted for other services' WHERE CUST_ID = '312'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2014-02-05', REASON = 'Service discontinuation' WHERE CUST_ID = '326'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2004-06-14', REASON = 'Opted for other services' WHERE CUST_ID = '411'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2001-09-10', REASON = 'Unhappy with service' WHERE CUST_ID = '456'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2019-05-25', REASON = 'Service discontinuation' WHERE CUST_ID = '559'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2004-01-31', REASON = 'Unhappy with service' WHERE CUST_ID = '569'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2017-09-26', REASON = 'Opted for other services' WHERE CUST_ID = '611'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2008-08-28', REASON = 'Relocation' WHERE CUST_ID = '616'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2015-10-04', REASON = 'Service discontinuation' WHERE CUST_ID = '617'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2015-06-30', REASON = 'Relocation' WHERE CUST_ID = '655'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2013-05-13', REASON = 'Service discontinuation' WHERE CUST_ID = '678'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2010-11-06', REASON = 'Unhappy with service' WHERE CUST_ID = '703'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2017-09-30', REASON = 'Opted for other services' WHERE CUST_ID = '713'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2010-02-20', REASON = 'Opted for other services' WHERE CUST_ID = '746'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2011-02-21', REASON = 'Service discontinuation' WHERE CUST_ID = '797'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2012-01-01', REASON = 'Opted for other services' WHERE CUST_ID = '801'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2019-01-13', REASON = 'Relocation' WHERE CUST_ID = '847'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2015-01-08', REASON = 'Service discontinuation' WHERE CUST_ID = '884'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2011-03-19', REASON = 'Relocation' WHERE CUST_ID = '897'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2016-01-31', REASON = 'Unhappy with service' WHERE CUST_ID = '912'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2016-12-15', REASON = 'Unhappy with service' WHERE CUST_ID = '920'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2014-01-22', REASON = 'Opted for other services' WHERE CUST_ID = '931'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2016-07-23', REASON = 'Service discontinuation' WHERE CUST_ID = '942'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2018-12-25', REASON = 'Relocation' WHERE CUST_ID = '972'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2012-12-23', REASON = 'Relocation' WHERE CUST_ID = '977'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2018-12-01', REASON = 'Relocation' WHERE CUST_ID = '994'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2017-11-30', REASON = 'Unhappy with service' WHERE CUST_ID = '1027'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2019-05-30', REASON = 'Unhappy with service' WHERE CUST_ID = '1056'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2018-01-31', REASON = 'Opted for other services' WHERE CUST_ID = '1065'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2019-06-27', REASON = 'Relocation' WHERE CUST_ID = '1072'; 
UPDATE [mumdab].[customer].[custdetails] SET END_DTE = '2018-12-31', REASON = 'Unhappy with service' WHERE CUST_ID = '1074'; 